name: <a href="https://www.facebook.com/mskn10"> JR MUSCAAN </a>
markdown: redcarpet
highlighter: pygments
permalink: :title
exclude: [README.md, LICENSE, Makefile]

# Information for the Atom feed
gereksiz:
   author: "Muskan Lamsal"
   email: "sportymskn@gmail.com"
